### ISSUE TITLE
Consolidated bundling [bounty: $250]

### ISSUE THREAD

**Issue by robingustafsson** [k6io/postman-to-k6#25]
Only bundle the necessary third-party browserified node.js deps when they're actually needed to fully convert a collection.

**Comment by robingustafsson** [comment]
https://www.bountysource.com/issues/72323804-consolidated-bundling-bounty-250

**Comment by bookmoons** [comment]
[`bookmoons/consolidate-bundling`](https://github.com/bookmoons/postman-to-k6/tree/bookmoons/consolidate-bundling) has something for this, but I think it conflicts with an open PR. Will return to this after that's closed.

**Comment by alromh87** [comment]
Hello, is this still needed?

**Comment by simskij** [comment]
@alromh87: Thanks for reaching out! I don't think so, but let me check and get back to you.
