### ISSUE TITLE
Is --skip-post working ?

### ISSUE THREAD

**Issue by nathan-boulestin** [k6io/postman-to-k6#70]
Hi,

I have a lot of "unsupported features" in my postman "Tests".
I thought "--skip-post" has meant to remove those tests scripts from the final k6 script,
but it appears they are still in my k6 script after the conversion (resulting in errors during k6 execution)

Is the tag --skip-post meant to remove the tests or am I misunderstanding the tag ?
If yes, why are the tests script still in the k6-script.js ?

Thanks

**Comment by nathan-boulestin** [comment]
Hi,
I have investigated a bit about the --skip-pre/post feature an found 2 issues: 

 - The version delivered this npm or yarn (npm install -D postman-to-k6 / yarn add postman-to-k6) is 1.1.0 not 1.3.0. And the version in package.json for 1.3.0 release is 1.0.0

 - The --separate tag dont work in 1.3.0 due to --skip-pre/post feature, see the picture
![bug p2k6](https://user-images.githubusercontent.com/72744989/96453035-36a27c00-121a-11eb-9bc6-90c12fbde4a9.png)

Is there any planned update of the converter ?

Thanks

**Comment by simskij** [comment]
A fix for this was released today to both dockerhub and npm. Please download v1.4.0 and let us know if it still doesn't work.
