### ISSUE TITLE
Overwrite request header "application/x-www-form-urlencoded", when none is specified

### ISSUE THREAD

**Issue by thim81** [k6io/postman-to-k6#81]
The Postman requests always seems to fallback to the request header "application/x-www-form-urlencoded", when none is specified.

Is there a way to overwrite this behaviour?

**Comment by simskij** [comment]
Hi @thim81,

No, unfortunately not. This is the default behavior of k6, as described in https://k6.io/docs/javascript-api/k6-http/post-url-body-params.

Feel free to raise a ticket in https://github.com/loadimpact/k6 with your suggestion.

Best,
Simme

**Comment by thim81** [comment]
Hi @simskij 

Related to this, I'm looking into way to set the "headers" globally to overwrite the default" x-www-form-urlencoded".
It seems that it is not (yet) supported https://github.com/k6io/k6/issues/761#issuecomment-782031960 .

I might have a feature request, but before I try to figure how to code it as a PR, I wanted to receive your input, if you think it is valuable.

Currently the package support "options" for setting Postman related data & variables (https://github.com/k6io/postman-to-k6#options)

It would help to be able to pass the  K6 "options", that are being used in the generate script.js file

`export let options = { maxRedirects: 4 };`

From
```
// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";
import { group } from "k6";
import "./requests/Api/Get-all-list-configurations.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    baseUrl: "https://example.com/api"
  },
  environment: {
    baseUrl: "https://example.com/api",
  }
}); 
....
```

The feature request would be pass a K6 options object that will extend/overwrite the `export let options`

Idea:

--k6-options ./k6-options.json

which would contain custom options like `{ maxRedirects: 6, headers: { 'Content-Type': 'application/json' } }`

Which would result in 

`export let options = { maxRedirects: 6, headers: { 'Content-Type': 'application/json' } };`

or even a import reference to the "k6-options.json" file itsel.
