### ISSUE TITLE
Missing autogenerated headers

### ISSUE THREAD

**Issue by Eomm** [k6io/postman-to-k6#82]
Postman adds by default the `'Content-Type': 'application/json'` on POST with a json body.

This header is not evaluated on k6 script generation.
Could it be possible to add it?
Could you guide me through the code?

Thanks

**Comment by simskij** [comment]
Definitely!  Just add it to the request object, like this:

```diff
    postman[Request]({
      name: "DELETE Request",
      id: "f167509c-88df-4965-8ede-30d376b71bd4",
      method: "DELETE",
      address: "https://postman-echo.com/delete",
      data: "test",
+      headers: {
+        "Content-Type": "application/json"
 +     }
});
```

You may even add the header explicitly in postman prior to converting your collection. 

Hope that helps!

Best,
Simme
