### ISSUE TITLE
Add converter version (1.3.0) on npm and docker hub

### ISSUE THREAD

**Issue by dbacelar4i** [k6io/postman-to-k6#86]
Hi,

I need to use "--skip-post" to remove some tests during conversion, but it is only available on version **1.3.0**.
The latest version available for npm and docker hub is **1.1.0**.

It would be possible to update the version on both?

Thanks.

**Comment by simskij** [comment]
Hey!

Sorry for the delay! 1.4.0 was released to both today.

Best,
Simme
