### ISSUE TITLE
Feature request - Pass Request default options

### ISSUE THREAD

**Issue by thim81** [k6io/postman-to-k6#87]
Hi @simskij 

Related to #81 , I'm looking into way to set the "headers" globally to overwrite the default" x-www-form-urlencoded".
It seems that it is not (yet) supported https://github.com/k6io/k6/issues/761#issuecomment-782031960 .

I might have a feature request, but before I try to figure how to code it as a PR, I wanted to receive your input, if you think it is valuable.

Currently the package support "options" for setting Postman execution related data & variables (https://github.com/k6io/postman-to-k6#options)

It would help to be able to pass the  Request "options", that are being used in the generated script.js file

```
import "../../libs/shim/urijs.js";

postman[Symbol.for("define")]({
  name: "Get all list configurations",
  id: "efc9d5ad-c0f1-4f41-ae17-e903fa56f82b",
  method: "GET",
  address: "{{baseUrl}}/lists/v2?$top=100&$skip=0&$count=false",
  headers: {
    "X-ApiKey": "{{username}}:{{password}}"
  },
  post(response) {
    // Validate status 2xx
    pm.test("[GET] /lists/v2 - Status code is 2xx", function() {
      pm.response.to.be.success;
    });
  }
});
```

The feature request would be pass a Request options object that will extend/overwrite the Postman Request methods like the "headers".

Idea:

--request-options ./request-headers.json

which would contain custom options like `{ headers: { 'Content-Type': 'application/json' } }`

Which would result in the Postman request, that gets extended by the passed on request headers.
This would be "default" options that you pass, which would apply for all requests.

```
import "../../libs/shim/urijs.js";

postman[Symbol.for("define")]({
  name: "Get all list configurations",
  id: "efc9d5ad-c0f1-4f41-ae17-e903fa56f82b",
  method: "GET",
  address: "{{baseUrl}}/lists/v2?$top=100&$skip=0&$count=false",
  headers: {
    "X-ApiKey": "{{username}}:{{password}}",
    'Content-Type": "application/json"
  },
  post(response) {
    // Validate status 2xx
    pm.test("[GET] /lists/v2 - Status code is 2xx", function() {
      pm.response.to.be.success;
    });
  }
});
```

Where the "headers" section got extended from 

```
headers: {
    "X-ApiKey": "{{username}}:{{password}}"
  }
```

to 

```
headers: {
    "X-ApiKey": "{{username}}:{{password}}",
    'Content-Type": "application/json"
  }

```

**Comment by thim81** [comment]
Or another would be to provide support in the Postman request for passing that are globally defined.

https://k6.io/docs/javascript-api/k6-http/params/

Example
```
export default function () {
  let params = {
    cookies: { my_cookie: 'value' },
    headers: { 'X-MyHeader': 'k6test' },
    redirects: 5,
    tags: { k6test: 'yes' },
  };
  let res = http.get('https://k6.io', params);
}
```

I'm not sure if the Postman request function uses all the "options"?

I tried this, but it does not seem to work, or am I missing something?

Example script.js file

```
// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";
import { group } from "k6";
import "./requests/Lists/Get-all-list-configurations.js";

export let options = { maxRedirects: 4 , headers: { 'Content-Type': 'application/json' } };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    baseUrl: "https://example.com/api"
  },
  environment: {
    baseUrl: "https://example.com/api"
  }
});

...
```

**Comment by simskij** [comment]
Hi,

Got it! Looks really good. I'll try to process the PRs as soon as possible, although I'm quite swamped at the moment so I can't promise I'll get to it this week. Thanks again for your excellent contributions! 🙇🏼 

Best,
Simme

**Comment by thim81** [comment]
@simskij Take your time. Don't need to rush it. I have made a merged branch with which I am using the PRs combined, so I can use it until you have tested it. 

Thank you for the excellent package.
